# Generated by Django 2.2.1 on 2019-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'content', 'verbose_name_plural': 'contents'},
        ),
        migrations.RenameField(
            model_name='content',
            old_name='data_add',
            new_name='date_add',
        ),
    ]
